- name: check conditions
  hosts: localhost
  tasks:
    - name: check user expense exists or not
      ansible.builtin.command: id expense
      ignore_errors: true
      register: USER
    - name: display user details
      ansible.builtin.debug:
        msg: "{{USER}}"
    - name: create user expense
      ansible.builtin.command: useradd expense
      when: USER.failed is true
