- name: Install nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: yes