- name: remove duplicates
  hosts: localhost
  vars_prompt:
    - name: mylist
      prompt: enter list
      private: no
  tasks:
    - name: remove duplicates from lists
      ansible.builtin.debug:
        msg: "{{ mylist | unique }}"