- name: uppercase with filters
  hosts: localhost
  vars_prompt:
    - name: message
      prompt: enter message
      private: no
  tasks:
    - name: display message in uppercase
      ansible.builtin.debug:
        msg: "{{ message | upper }}"
    - name: display message in lowercase
      ansible.builtin.debug:
        msg: "{{ message | lower }}"