- name: variables from prompt
  hosts: localhost
  vars_prompt:
    - name: Course
      prompt: please enter Course
      private: false
    - name: Duration
      prompt: please enter Duration
      private: true
    - name: Trainer
      prompt: please enter Trainer
      private: true
  tasks:
    - name: display variables from prompt
      ansible.builtin.debug:
        msg: "Hello course is {{Course}} , duration is {{Duration}} and {{Trainer}}"