- name: list to dict items
  hosts: localhost
  vars:
    mydict:
      Course: DevOps
      Trainer: Siva
      Duration: 123hrs
  tasks:
    - name: convert list to  dict items
      ansible.builtin.debug:
        msg: "{{ mydict | dict2items }}"