- name: variables priority
  hosts: localhost
  vars:
    Course: DEvops
    Trainer: Raghu
    Duration: 123hrs
  vars_files:
    - vars.yml
  vars_prompt:

  tasks:
    - name: get priorities
      ansible.builtin.debug:
        msg: "Hello this {{Course}} , {{Duration}} and {{Trainer}} "
